'''
文件图标映射：根据文件扩展名或文件名返回对应的 emoji 图标
'''

from pathlib import Path

FILE_ICONS = {
    '.csv': '📊',
    '.html': '🌐',
    '.ini': '⚙️',
    '.log': '📋',
    '.md': '📝',
    '.markdown': '📝',
    '.rst': '📖',
    '.toml': '📋',
    '.tsv': '📊',
    '.txt': '📄',
    '.xml': '📰',
    '.yaml': '📋',
    '.yml': '📋',
    '.conf': '⚙️',
    '.cfg': '⚙️',
    '.tex': '📚',
    '.vtt': '📝',
    '.srt': '📝',
    '.c': '🔧',
    '.cpp': '🔧',
    '.cs': '🔷',
    '.dart': '🎯',
    '.go': '🐹',
    '.h': '🔧',
    '.ipynb': '📓',
    '.java': '☕',
    '.js': '📜',
    '.jsx': '⚛️',
    '.kt': '🅺',
    '.lua': '🌙',
    '.m': '🍎',
    '.php': '🐘',
    '.pl': '🐪',
    '.py': '🐍',
    '.pyc': '🐍',
    '.pyd': '🐍',
    '.r': '📊',
    '.rb': '💎',
    '.rs': '🦀',
    '.sh': '🐚',
    '.sql': '🗄️',
    '.swift': '🐦',
    '.ts': '📜',
    '.tsx': '⚛️',
    '.vue': '🖖',
    '.scala': '🔵',
    '.groovy': '🚀',
    '.hs': 'λ',
    '.f': '🔬',
    '.fs': '🔷',
    '.app': '📱',
    '.bat': '⚙️',
    '.bin': '🔧',
    '.cmd': '⚙️',
    '.dll': '🔗',
    '.exe': '⚙️',
    '.jar': '📦',
    '.so': '🔗',
    '.msi': '📦',
    '.deb': '📦',
    '.rpm': '📦',
    '.7z': '🗜️',
    '.bz2': '🗜️',
    '.gz': '🗜️',
    '.rar': '🗜️',
    '.tar': '🗜️',
    '.xz': '🗜️',
    '.zip': '🗜️',
    '.zst': '🗜️',
    '.lzma': '🗜️',
    '.cab': '🗜️',
    '.ai': '🎨',
    '.bmp': '🖼️',
    '.gif': '🖼️',
    '.ico': '🔣',
    '.jpeg': '🖼️',
    '.jpg': '🖼️',
    '.pdf': '📄',
    '.psd': '🖌️',
    '.svg': '🎨',
    '.tiff': '🖼️',
    '.webp': '🖼️',
    '.png': '🖼️',
    '.heic': '🖼️',
    '.raw': '📷',
    '.indd': '🎨',
    '.avi': '🎬',
    '.flac': '🎵',
    '.mkv': '🎬',
    '.mov': '🎬',
    '.mpeg': '🎬',
    '.mpg': '🎬',
    '.mp3': '🎵',
    '.mp4': '🎬',
    '.ogg': '🎵',
    '.wav': '🎵',
    '.wmv': '🎬',
    '.webm': '🎬',
    '.aac': '🎵',
    '.m4a': '🎵',
    '.flv': '🎬',
    '.3gp': '🎬',
    '.doc': '📄',
    '.docx': '📄',
    '.ppt': '🎤',
    '.pptx': '🎤',
    '.xls': '📊',
    '.xlsx': '📊',
    '.odt': '📄',
    '.ods': '📊',
    '.odp': '🎤',
    '.bak': '💾',
    '.gitignore': '🚫',
    '.img': '📀',
    '.iso': '📀',
    '.json': '🔑',
    '.lock': '🔒',
    '.patch': '🧩',
    '.tmp': '⏳',
    '.torrent': '📥',
    'LICENSE': '📜',
    'README.md': '📖',
    '.cer': '🔒',
    '.crt': '🔒',
    '.key': '🔑',
    '.pub': '🔑',
    '.db': '🗄️',
    '.sqlite': '🗄️',
    '.mdb': '🗄️',
    '.url': '🔗',
    '.lnk': '🔗'
}

DEFAULT_FILE_ICON = '📄'
DIRECTORY_ICON = '📂'


def get_file_icon(file_name: str) -> str:
    """根据文件名或扩展名获取对应的图标"""
    if file_name in FILE_ICONS:
        return FILE_ICONS[file_name]
    ext = Path(file_name).suffix.lower()
    return FILE_ICONS.get(ext, DEFAULT_FILE_ICON)
